model:
    arch: refinenet
data:
    dataset: my
    train_split: train
    val_split: val
    img_rows: 400
    img_cols: 400
    path: dataset/05-Vahingen-train8-rotate-edit-precode/
training:
#    train_iters: 300000
    train_epoch: 200
    batch_size: 8
    val_interval: 50
#    val_epoch: 1
    n_workers: 16
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-3
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: True
    lr_schedule:
    resume: refinenet_my_best_model.pkl
